version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: todo-app
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_admin
    volumes:
      - ./.docker/data/mongodb:/data/db
      - ./.docker/db-init:/docker-entrypoint-initdb.d
    secrets:
      - mongo_admin
      - database_user

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_admin
      ME_CONFIG_MONGODB_SERVER: mongodb
    secrets:
      - mongo_admin

secrets:
  mongo_admin:
    file: ./.docker/secrets/mongo-admin.txt
  database_user:
    file: ./.docker/secrets/database-user.txt
   